### ISSUE TITLE
Unable to Add Component in Content Constructor - Uncaught TypeError in content-constructor.js

### ISSUE THREAD

**Issue by tingyeeh** [magesuite/magesuite#124]
---

**Title:** Bug: Unable to Add Component in Content Constructor - Uncaught TypeError in content-constructor.js

**Description:**
There is an issue with the `content-constructor` module in Magesuite. When I try to add a component in the Content Constructor, it fails to add the component. The browser console shows the following errors:

```
content-constructor.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at VueComponent.sortComponentsBySections (content-constructor.js:1:69534)
    at VueComponent.sortComponentsBySections (vue.js:220:74)
    at VueComponent.ready (content-constructor.js:1:63854)
    at t._callHook (vue.js:8046:23)
    at VueComponent.e (vue.js:9268:12)
    at VueComponent.i (vue.js:9065:12)
    at t.$emit (vue.js:9146:24)
    at t._callHook (vue.js:8049:12)
    at s (vue.js:8008:15)
    at Array.forEach (<anonymous>)

content-constructor.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'defaults')
    at VueComponent.getComponentConfigurator (content-constructor.js:1:357174)
    at VueComponent.<anonymous> (vue.js:220:29)
    at VueComponent.onPickComponent (content-constructor.js:1:4125)
    at VueComponent.onPickComponent (vue.js:220:29)
    at VueComponent.eval (eval at Lt (vue.js:2859:14), <anonymous>:3:15)
    at HTMLAnchorElement.n (vue.js:8250:12)
    at HTMLAnchorElement.<anonymous> (vue.js:5047:22)
```

**Steps to Reproduce:**
1. Open Content Constructor in Magesuite.
2. Attempt to add a new component.
3. Observe the errors in the browser console.

**Expected Behavior:**
The component should be added successfully without any errors.

**Actual Behavior:**
The component is not added, and the browser console shows `Uncaught TypeError` related to reading properties of undefined.

**Environment:**
- Magesuite version: 13.0.0
- Browser: Microsoft Edge version 125.0.2535.67 (64-bit)
- OS: Nginx Debian 12

**Additional Context:**
Please investigate the root cause of these `Uncaught TypeError` errors and provide a fix.

---

Feel free to copy and paste this report directly into your GitHub issue tracker.

![image](https://github.com/magesuite/magesuite/assets/15965783/8f9b8a87-b1c4-40b3-a9d7-b212d947a4a4)

**Comment by diwipl** [comment]
Hi

Thank you for the report.

The error suggests that theme-creativeshop was not build and/or was not set as default theme in the admin panel.

**Comment by tingyeeh** [comment]
> Hi
> 
> Thank you for the report.
> 
> The error suggests that theme-creativeshop was not build and/or was not set as default theme in the admin panel.



> Hi
> 
> Thank you for the report.
> 
> The error suggests that theme-creativeshop was not build and/or was not set as default theme in the admin panel.

Thanks, it works

**Comment by tingyeeh** [comment]
> Hi
> 
> Thank you for the report.
> 
> The error suggests that theme-creativeshop was not build and/or was not set as default theme in the admin panel.

Thanks, it works
