### ISSUE TITLE
Grouped products breaking cart page

### ISSUE THREAD

**Issue by Mugentoki** [magesuite/magesuite#51]
Adding a grouped product to cart is breaking the cart page. Only the product itself is visible but without styles. All other stuff like header, footer and the page itself are missing.
It's working fine with simple products though...

```
PHP Fatal error: Uncaught Error: Call to a member function setData() on boolean in .../htdocs/app/design/frontend/creativestyle/theme-creativeshop/Magento_Checkout/templates/cart/item/default.phtml:105
Stack trace:
#0 .../htdocs/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#1 .../htdocs/vendor/magento/framework/View/Element/Template.php(271): Magento\\Framework\\View\\TemplateEngine\\Php->render(Object(Magento\\GroupedProduct\\Block\\Cart\\Item\\Renderer\\Grouped\\Interceptor), '/var/www/share/...', Array)
#2 .../htdocs/generated/code/Magento/GroupedProduct/Block/Cart/Item/Renderer/Grouped/Interceptor.php(505): Magento\\Framework\\View\\Element\\Template->fetchView('/var/www/share/...')
#3 .../htdocs/vendor/magento/framework/View/Element/Template.php(301): Magento\\GroupedProduc...'
```

Magento Version: 2.3.4
MageSuite Version: 5.0.0
theme-creativeshop: v8.13.5
MageSuite Packages: Don't know which one could cause a bug in cart page, let me know which package versions you need

**Comment by diwipl** [comment]
Fixed by following commit: https://github.com/magesuite/theme-creativeshop/commit/899da51c1e67918bb06cf03dcd00ab2bd3fd3129

You have to wait for it to be tagged and released.

Other way is to alias dev-next as v8.13.5 in your main composer.json

**Comment by diwipl** [comment]
I have to reopen this issue. Seems like above fix broke simple products in cart page. I've reverted commit (this should be synchronised with github in next hour).

Will let you know when new fix is ready.
